print("DAU: PLYM4")
print("Author: Andy Wills")
print("Date: 2014-06-06")
print("Load and aggregate the summary files from PLYM1, PLYM2, and PLYM3")
load('plym1sum.RData')
exp <- bigmf$exp
cond <- bigmf$cond
os <- bigmf$os
model <- bigmf$model
bis <- bigmf$bis
load('plym2sum.RData')
exp <- c(exp,bigmf$exp)
cond <- c(cond,bigmf$cond)
os <- c(os,bigmf$os)
model <- c(model,bigmf$model)
bis <- c(bis,bigmf$bis)
load('plym3sum.RData')
exp <- c(exp,bigmfu$exp)
cond <- c(cond,bigmfu$cond)
os <- c(os,bigmfu$os)
model <- c(model,bigmfu$model)
bis <- c(bis,bigmfu$bis)
rm(bigmf,bigmfu)
bigmf <- data.frame(exp,cond,os,model,bis)
bigmf$model[bigmf$model == 2] <- 1
print("Now the analyses in the order they are discussed in the Supplementary Materials")
print("Trad - Exp 2 - LTP")
cdta <- subset(bigmf, bigmf$cond == 2 & bigmf$exp == 'PLYM1')
print(cor.test(cdta$os, cdta$bis))
print("Trad - Exp 3A- LTP")
cdta <- subset(bigmf, cond == 2 & exp == 'PLYM2')
print(cor.test(cdta$os, cdta$bis))
print("Model - Exp 3A - LTP - UD vs OS")
cdta <- subset(bigmf, exp == 'PLYM2' & cond == 2)
tdta <- subset(cdta, model == 1 | model == 3)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("Model - Exp 3A - LTP - UD vs ID")  
tdta <- subset(cdta, model == 1 | model == 4)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("Model - Exp 3A - LTP - OS vs ID")    
tdta <- subset(cdta, model == 3 | model == 4)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("Trad - Exp 2 - HTP")
cdta <- subset(bigmf, cond == 1 & exp == 'PLYM1')
print(cor.test(cdta$os, cdta$bis))
print("Trad - Exp 3A - HTP")
cdta <- subset(bigmf, cond == 1 & exp == 'PLYM2')
print(cor.test(cdta$os, cdta$bis))
print("Trad - Exp 3B - HTP")
cdta <- subset(bigmf, cond == 1 & exp == 'PLYM3')
print(cor.test(cdta$os, cdta$bis))
print("Model - Exp 3A - HTP - OS vs UD")
cdta <- subset(bigmf, exp == 'PLYM2' & cond == 1)
tdta <- subset(cdta, model == 1 | model == 3)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("Model - Exp 2 - HTP - UD vs ID")
cdta <- subset(bigmf, exp == 'PLYM1' & cond == 1)
tdta <- subset(cdta, model == 1 | model == 4)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("10 pairwise comparisons")
cdta <- bigmf
e2ltp <- subset(cdta, cond == 2 & exp == 'PLYM1') #1
e2htp <- subset(cdta, cond == 1 & exp == 'PLYM1') #2
e3altp <- subset(cdta, cond == 2 & exp == 'PLYM2') #3
e3ahtp <- subset(cdta, cond == 1 & exp == 'PLYM2') #4
e3bhtp <- subset(cdta, cond == 1 & exp == 'PLYM3') #5
print("E2LTP vs. E2HTP")
tdta <-rbind(e2ltp,e2htp)
print(t.test(bis ~ cond, data = tdta,var.equal=TRUE))
print("E2LTP vs. E3ALTP")
tdta <-rbind(e2ltp,e3altp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E2HTP vs. E3AHTP")
tdta <-rbind(e2ltp,e3ahtp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E2HTP vs. E3BHTP") 
tdta <-rbind(e2ltp,e3bhtp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E2HTP vs. E3ALTP")
tdta <-rbind(e2htp,e3altp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E2HTP vs. E3AHTP")
tdta <-rbind(e2htp,e3ahtp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E2HTP vs. E3BHTP")
tdta <-rbind(e2htp,e3bhtp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E3ALTP vs. E3AHTP")
tdta <-rbind(e3altp,e3ahtp)
print(t.test(bis ~ cond, data = tdta,var.equal=TRUE))
print("E3ALTP vs. E3BHTP")
tdta <-rbind(e3altp,e3bhtp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("E3AHTP vs. E3BHTP")
tdta <-rbind(e3ahtp,e3bhtp)
print(t.test(bis ~ exp, data = tdta,var.equal=TRUE))
print("Combination of all conditions except Exp3A LTP")
cdta1 <- subset(bigmf, exp != 'PLYM2')
cdta2 <- subset(bigmf, exp == 'PLYM2' & cond == 1)
cdta <- rbind(cdta1,cdta2)
print("Trad")
print(cor.test(cdta$os, cdta$bis))
print("Model - UD vs OS")
tdta <- subset(cdta, model == 1 | model == 3)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("Model - UD vs ID")
tdta <- subset(cdta, model == 1 | model == 4)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))
print("Model - OS vs ID")
tdta <- subset(cdta, model == 3 | model == 4)
print(t.test(bis ~ model, data = tdta,var.equal=TRUE))

