GLM ESA_B_1 ESA_B_2 ESA_B_3 ESA_B_4 ESA_B_5 ESA_B_6 ESA_B_7 ESA_B_8 BY Group
  /WSFACTOR=Trial 8 Polynomial 
  /METHOD=SSTYPE(3)
  /PRINT=DESCRIPTIVE ETASQ 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Trial 
  /DESIGN=Group.

SORT CASES  BY Group.
SPLIT FILE LAYERED BY Group.

GLM ESA_B_1 ESA_B_2 ESA_B_3 ESA_B_4 ESA_B_5 ESA_B_6 ESA_B_7 ESA_B_8
  /WSFACTOR=Trial 8 Polynomial 
  /METHOD=SSTYPE(3)
  /PRINT=DESCRIPTIVE ETASQ 
  /CRITERIA=ALPHA(.05)
  /WSDESIGN=Trial.
  